[build.env]
passthrough = [
	"RUSTFLAGS",
	"RUST_TEST_THREADS"
]
[target.loongarch64-unknown-linux-gnu]
image = "ghcr.io/loongarchlinux/archlinux:latest"
image.toolchain = ["loongarch64-unknown-linux-gnu"]
